DROP TABLE IF EXISTS `ATHLETE`;

CREATE TABLE `ATHLETE`(
	`ID_ATHLETE` int(10) unsigned NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(128) NOT NULL,
	`SURNAME` VARCHAR(256) DEFAULT NULL,
	PRIMARY KEY (`ID_ATHLETE`)	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
